ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "telegramOptOut" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "lastMarketingPromptAt" TIMESTAMP(3);
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "marketingPromptCount" INTEGER NOT NULL DEFAULT 0;
